version: '2'
services:
  solr-zk-1:
    build:
      context: .
      dockerfile: Dockerfile-cloud
    container_name: solr-zk-1
    image: hardikdocker/solrcloud-zookeeper-docker
    environment:
      - ZKID=1
      - SOLR_DATADIR=/solr-data
      - ZK_DATADIR=/zk-data
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
    #command: ["echo $$ZKID >> /zk-data/myid", "./zk/bin/zkServer.sh start" , "./solr/bin/solr -cloud -z solr-zk-1:2181,solr-zk-2:2181,solr-zk-3:2181 -s /solr-data"]
    networks:
      solr_net:
        ipv4_address: 172.16.238.11

  solr-zk-2:
    build:
      context: .
      dockerfile: Dockerfile-cloud
    container_name: solr-zk-2
    image: hardikdocker/solrcloud-zookeeper-docker
    environment:
      - ZKID=2
      - SOLR_DATADIR=/solr-data
      - ZK_DATADIR=/zk-data
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
    extra_hosts:
      - "solr-zk-1:172.16.238.11"
      - "solr-zk-2:172.16.238.12"
      - "solr-zk-3:172.16.238.13"
    #command: ["touch /zk-data/myid", "echo $$ZKID >> /zk-data/myid", "./zk/bin/zkServer.sh start" , "./solr/bin/solr -cloud -z solr-zk-1:2181,solr-zk-2:2181,solr-zk-3:2181 -s /solr-data"]
    networks:
      solr_net:
        ipv4_address: 172.16.238.12

  solr-zk-3:
    build:
      context: .
      dockerfile: Dockerfile-cloud
    container_name: solr-zk-3
    image: hardikdocker/solrcloud-zookeeper-docker
    environment:
      - ZKID=3
      - SOLR_DATADIR=/solr-data
      - ZK_DATADIR=/zk-data
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
    #command: ["touch /zk-data/myid", "echo $$ZKID >> /zk-data/myid", "./zk/bin/zkServer.sh start" , "./solr/bin/solr -cloud -z solr-zk-1:2181,solr-zk-2:2181,solr-zk-3:2181 -s /solr-data"]
    networks:
      solr_net:
        ipv4_address: 172.16.238.13
networks:
  solr_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1

