version: '2'
services:
  elastic-kibana:
    container_name: elastic-kibana
    build:
      context: .
      dockerfile: Dockerfile-es-kb
    command: ./start.sh
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5601:5601"
      - "24284:24284"
      - "24224:24224"
    networks:
      solr_net:
        ipv4_address: 172.16.238.21
  zoo1:
    container_name: zoo1
    depends_on:
      - elastic-kibana
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: "172.16.238.21:24224"
    build:
      context: .
      dockerfile: Dockerfile-cloud-1
    command: ./start.sh
    environment: 
      - ZKID=1
    tty: false
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
      - "elasticsearch:172.16.238.21"
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    networks:
      solr_net:
        ipv4_address: 172.16.238.11
  zoo2:
    container_name: zoo2
    depends_on:
      - elastic-kibana
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: "172.16.238.21:24224"
    build:
      context: .
      dockerfile: Dockerfile-cloud-2
    command: ./start.sh
    environment: 
      - ZKID=2
    tty: false
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
      - "elasticsearch:172.16.238.21"
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    networks:
      solr_net:
        ipv4_address: 172.16.238.12
  zoo3:
    container_name: zoo3
    depends_on:
      - elastic-kibana
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: "172.16.238.21:24224"
    build:
      context: .
      dockerfile: Dockerfile-cloud-3
    command: ./start.sh
    environment:
      - ZKID=3
    tty: false
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
      - "elasticsearch:172.16.238.21"
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    networks:
      solr_net:
        ipv4_address: 172.16.238.13
  zoo4:
    container_name: zoo4
    depends_on:
      - elastic-kibana
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: "172.16.238.21:24224"
    build:
      context: .
      dockerfile: Dockerfile-cloud-4
    command: ./start.sh
    environment:
      - ZKID=4
    tty: false
    extra_hosts:
      - "zoo4:172.16.238.14"
      - "zoo5:172.16.238.15"
      - "elasticsearch:172.16.238.21"
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    networks:
      solr_net:
        ipv4_address: 172.16.238.14
  zoo5:
    container_name: zoo5
    depends_on:
      - elastic-kibana
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: "172.16.238.21:24224"
    build:
      context: .
      dockerfile: Dockerfile-cloud-5
    container_name: zoo5
    command: ./start.sh
    environment:
      - ZKID=5
    tty: false
    extra_hosts:
      - "zoo4:172.16.238.14"
      - "zoo5:172.16.238.15"
      - "elasticsearch:172.16.238.21"
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    networks:
      solr_net:
        ipv4_address: 172.16.238.15
  node-fusion:
    container_name: node-fusion
    depends_on:
      - zoo4
      - zoo5
      - elastic-kibana
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: "172.16.238.21:24224"
    build:
      context: .
      dockerfile: Dockerfile-fusion
    ports:
      - "8764:8764"
      - "8983:8983"
      - "8765:8765"
      - "8984:8984"
      - "8766:8766"
      - "8769:8769"
      - "3000:3000"
    extra_hosts:
      - "zoo1:172.16.238.11"
      - "zoo2:172.16.238.12"
      - "zoo3:172.16.238.13"
      - "zoo4:172.16.238.14"
      - "zoo5:172.16.238.15"
      - "elasticsearch:172.16.238.21"
    volumes:
      - "./shared:/usr/local/shared"
    command: ./start.sh
    networks:
      solr_net:
        ipv4_address: 172.16.238.16
networks:
  solr_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1

