services:
  solr-zk-1:
    container_name: solr-zk-1
    image: hardikdocker/solrcloud-zookeeper-docker
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    environment:
      - ZKID=1
      - SOLR_DATADIR=/solr-data
      - ZK_DATADIR=/zk-data
    command: 
      echo "server.1=solr-zk-1:2888:3888" >> /zk/conf/zoo.cfg &&\
      echo "server.1=solr-zk-2:2888:3888" >> /zk/conf/zoo.cfg &&\
      echo "server.1=solr-zk-3:2888:3888" >> /zk/conf/zoo.cfg

  solr-zk-2:
    container_name: solr-zk-2
    image: hardikdocker/solrcloud-zookeeper-docker
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    environment:
      - ZKID=2
      - SOLR_DATADIR=/solr-data
      - ZK_DATADIR=/zk-data
    command: 
      echo "server.1=solr-zk-1:2888:3888" >> /zk/conf/zoo.cfg &&\
      echo "server.1=solr-zk-2:2888:3888" >> /zk/conf/zoo.cfg &&\
      echo "server.1=solr-zk-3:2888:3888" >> /zk/conf/zoo.cfg

  solr-zk-3:
    container_name: solr-zk-3
    image: hardikdocker/solrcloud-zookeeper-docker
    ports:
      - "8983"
      - "2181"
      - "2888"
      - "3888"
    environment:
      - ZKID=3
      - SOLR_DATADIR=/solr-data
      - ZK_DATADIR=/zk-data
    command: 
      echo "server.1=solr-zk-1:2888:3888" >> /zk/conf/zoo.cfg &&\
      echo "server.1=solr-zk-2:2888:3888" >> /zk/conf/zoo.cfg &&\
      echo "server.1=solr-zk-3:2888:3888" >> /zk/conf/zoo.cfg
